const createOffer = (id, nombre, descripcion, precio, extras = {}) => ({
  id,
  experience_id: id,
  nombre,
  descripcion,
  precio,
  moneda: "EUR",
  activa: true,
  ...extras,
});

export const demoSectorData = {
  winery: {
    account: {
      id: "sector-demo-winery",
      slug: "sector-demo-winery",
      nombre: "Celler Serra Alta (Demo)",
      activa: true,
      demo_publica: true,
      is_generic_sector_demo: true,
      sector: "winery",
      claim: "Converteix consultes en reserves d'enoturisme amb una atenció premium.",
      subtitulo: "Enoturisme boutique amb visites guiades, tastos i experiències privades.",
      descripcion_corta: "Celler familiar orientat a experiències premium i venda directa.",
      tono_marca: "proper, expert i elegant",
      propuesta_valor: "Atenció instantània per resoldre dubtes i accelerar la reserva.",
      faqs_texto: [
        "On esteu ubicats i com arribar-hi?",
        "Inclou opcions per a vegetarians?",
        "Puc reservar per a grups grans o empreses?",
      ],
      reglas_recomendacion: [
        "Si el client demana una primera visita, recomana el Tasting Essencial.",
        "Si busca celebració o grup reduït, proposa Reserva Privada amb maridatge.",
      ],
      reglas_objeciones: [
        "Si dubta pel preu, explica què inclou cada experiència i valor diferencial.",
        "Si no té data clara, ofereix pre-reserva flexible.",
      ],
      prompts_sugeridos: [
        "Quina experiència em recomanes per una parella?",
        "Teniu opcions premium amb maridatge?",
        "Com puc reservar una visita privada?",
      ],
      cta: "Reserva la teva experiència",
      idioma_defecto: "ca",
      idiomas_disponibles: ["ca", "es", "en"],
    },
    offers: [
      createOffer("winery-visit", "Visita al celler", "Recorregut guiat per vinyes i zona de criança amb explicació del procés d'elaboració.", 28),
      createOffer("winery-tasting", "Tasting Essencial", "Tast de 4 vins amb pica-pica local i introducció als perfils aromàtics.", 38),
      createOffer("winery-premium", "Tasting Premium", "Selecció de 6 vins reserva amb maridatge gastronòmic i sommelier dedicat.", 68),
      createOffer("winery-private", "Reserva Privada", "Experiència exclusiva per a grups reduïts amb espai privat i ritme personalitzat.", 320, { maximo_personas: 10 }),
    ],
  },
  professional_services: {
    account: {
      id: "sector-demo-professional-services",
      slug: "sector-demo-professional-services",
      nombre: "Nexia Advisory (Demo)",
      activa: true,
      demo_publica: true,
      is_generic_sector_demo: true,
      sector: "professional_services",
      claim: "Preventa consultiva que converteix consultes en projectes amb abast clar.",
      subtitulo: "Consultoria estratègica i operativa per pimes en creixement.",
      descripcion_corta: "Firma orientada a transformació comercial, processos i govern operatiu.",
      tono_marca: "clar, executiu i orientat a resultats",
      propuesta_valor: "Diagnòstic ràpid i proposta accionable des de la primera conversa.",
      faqs_texto: ["Treballen amb equips petits?", "Quins terminis té un projecte tipus?", "Feu suport continuat?"],
      reglas_recomendacion: [
        "Si el client no té diagnòstic, començar amb Auditoria Inicial.",
        "Si el projecte afecta diverses àrees, proposar Sessió Estratègica + Pla d'Implementació.",
      ],
      reglas_objeciones: [
        "Si demana pressupost tancat massa aviat, demanar context mínim per evitar sobrecostos.",
        "Si té urgència, oferir format sprint de 2 setmanes.",
      ],
      prompts_sugeridos: ["Necessito ordenar el procés comercial", "Quin servei és millor per una pime?", "Com funciona el seguiment mensual?"],
      cta: "Parlar amb un consultor",
      idioma_defecto: "es",
      idiomas_disponibles: ["es", "en", "ca"],
    },
    offers: [
      createOffer("ps-audit", "Auditoría inicial", "Análisis de situación actual, riesgos y oportunidades priorizadas.", 490),
      createOffer("ps-strategy", "Sesión estratégica", "Workshop de 90 minutos para definir objetivos, KPIs y roadmap.", 750),
      createOffer("ps-implementation", "Plan de implementación", "Diseño detallado por fases, responsables y entregables de 90 días.", 1900),
      createOffer("ps-premium", "Seguimiento premium", "Acompañamiento quincenal con comité de avance y ajustes continuos.", 1200),
    ],
  },
  clinic: {
    account: {
      id: "sector-demo-clinic",
      slug: "sector-demo-clinic",
      nombre: "Clínica Nova Salut (Demo)",
      activa: true,
      demo_publica: true,
      is_generic_sector_demo: true,
      sector: "clinic",
      claim: "Gestiona consultas de pacientes con información clara y derivación ordenada.",
      subtitulo: "Centro médico multidisciplinar con atención preventiva y tratamientos avanzados.",
      descripcion_corta: "Clínica privada enfocada en experiencia del paciente y continuidad asistencial.",
      tono_marca: "empático, profesional y tranquilizador",
      propuesta_valor: "Respuestas inmediatas para reducir carga de recepción y mejorar conversión de primeras visitas.",
      faqs_texto: ["¿Aceptan mutuas?", "¿Qué documentación debo traer?", "¿Ofrecen seguimiento tras tratamiento?"],
      reglas_recomendacion: ["Para nuevos pacientes, recomendar Primera visita médica.", "Si ya existe diagnóstico, ofrecer Revisión especializada."],
      reglas_objeciones: ["Si hay preocupación por precio, explicar cobertura y opciones de pack.", "Si necesita rapidez, proponer huecos de agenda prioritaria."],
      prompts_sugeridos: ["Necesito primera visita esta semana", "¿Qué opciones de seguimiento tenéis?", "¿Hay tratamientos premium?"],
      cta: "Solicitar primera visita",
      idioma_defecto: "es",
      idiomas_disponibles: ["es", "ca", "en"],
    },
    offers: [
      createOffer("clinic-first", "Primera visita", "Consulta inicial con valoración completa y plan recomendado.", 85),
      createOffer("clinic-review", "Revisión", "Visita de seguimiento para ajustar tratamiento y resolver dudas.", 55),
      createOffer("clinic-premium", "Tratamiento premium", "Programa intensivo con tecnología avanzada y monitorización clínica.", 640),
      createOffer("clinic-pack", "Pack de seguimiento", "3 revisiones + canal prioritario de soporte clínico durante 60 días.", 180),
    ],
  },
  local_business: {
    account: {
      id: "sector-demo-local-business",
      slug: "sector-demo-local-business",
      nombre: "Espai Servei Barri (Demo)",
      activa: true,
      demo_publica: true,
      is_generic_sector_demo: true,
      sector: "local_business",
      claim: "Atención comercial inmediata para no perder clientes de proximidad.",
      subtitulo: "Negocio local con servicios recurrentes y fidelización mensual.",
      descripcion_corta: "Operativa de barrio con alto volumen de consultas por WhatsApp y web.",
      tono_marca: "cercano, ágil y resolutivo",
      propuesta_valor: "Filtrado automático de consultas y cierre de citas más rápido.",
      faqs_texto: ["¿Atendéis sin cita?", "¿Tenéis bonos mensuales?", "¿Cuánto tarda cada servicio?"],
      reglas_recomendacion: ["Si es primera vez, ofrecer Servicio básico.", "Si valora calidad/precio a medio plazo, recomendar Bono mensual."],
      reglas_objeciones: ["Si duda por presupuesto, comparar ahorro frente a servicios sueltos.", "Si tiene prisa, ofrecer primer hueco disponible."],
      prompts_sugeridos: ["¿Tenéis hueco hoy por la tarde?", "¿Qué incluye el servicio premium?", "Explícame el bono mensual"],
      cta: "Reservar servicio",
      idioma_defecto: "es",
      idiomas_disponibles: ["es", "ca"],
    },
    offers: [
      createOffer("local-basic", "Servicio básico", "Atención estándar con resolución del caso más frecuente.", 29),
      createOffer("local-premium", "Servicio premium", "Servicio ampliado con prioridad y garantías extendidas.", 59),
      createOffer("local-bono", "Bono mensual", "Cuota mensual con servicios incluidos y precio preferente.", 99),
    ],
  },
  hospitality: {
    account: {
      id: "sector-demo-hospitality",
      slug: "sector-demo-hospitality",
      nombre: "Hotel Mirador Urbà (Demo)",
      activa: true,
      demo_publica: true,
      is_generic_sector_demo: true,
      sector: "hospitality",
      claim: "Incrementa reservas directas y upselling antes de la llegada.",
      subtitulo: "Hotel boutique con experiencias complementarias de fin de semana.",
      descripcion_corta: "Alojamiento urbano de 4 estrellas orientado a escapadas cortas.",
      tono_marca: "acogedor, elegante y orientado al detalle",
      propuesta_valor: "Asistente que responde disponibilidad, condiciones y extras en segundos.",
      faqs_texto: ["¿Incluye desayuno?", "¿Aceptan mascotas?", "¿Hay parking cercano?"],
      reglas_recomendacion: ["Si viaja en pareja, sugerir Habitación premium.", "Si busca experiencia completa, proponer Pack escapada."],
      reglas_objeciones: ["Si ve caro el premium, explicar extras incluidos.", "Si compara canales, destacar ventajas de reserva directa."],
      prompts_sugeridos: ["Busco habitación para este fin de semana", "¿Qué incluye el pack escapada?", "¿Tenéis opción premium?"],
      cta: "Consultar disponibilidad",
      idioma_defecto: "es",
      idiomas_disponibles: ["es", "en", "ca"],
    },
    offers: [
      createOffer("hotel-standard", "Habitación estándar", "Habitación doble con amenities y cancelación flexible.", 119),
      createOffer("hotel-premium", "Habitación premium", "Habitación superior con vistas, desayuno incluido y late checkout.", 179),
      createOffer("hotel-getaway", "Pack escapada", "2 noches + experiencia local + detalle de bienvenida.", 360),
    ],
  },
  tourism: {
    account: {
      id: "sector-demo-tourism",
      slug: "sector-demo-tourism",
      nombre: "Rutes Mediterrània (Demo)",
      activa: true,
      demo_publica: true,
      is_generic_sector_demo: true,
      sector: "tourism",
      claim: "Guía viajeros y convierte consultas en reservas confirmadas.",
      subtitulo: "Operador turístico especializado en experiencias culturales y de naturaleza.",
      descripcion_corta: "Agencia receptiva con tours diarios y experiencias privadas.",
      tono_marca: "inspirador, práctico y orientado al viajero",
      propuesta_valor: "Recomendación de rutas en función de perfil, fechas y presupuesto.",
      faqs_texto: ["¿En qué idiomas son los tours?", "¿Incluye transporte?", "¿Se puede cancelar?"],
      reglas_recomendacion: ["Si es primera visita a la ciudad, recomendar Tour básico.", "Si viaja en grupo o familia, ofrecer Pack privado."],
      reglas_objeciones: ["Si duda por tiempo, proponer itinerario corto.", "Si compara precio, resaltar guía oficial y logística incluida."],
      prompts_sugeridos: ["Quiero un tour para mañana", "¿Tenéis experiencias premium?", "Busco opción privada para familia"],
      cta: "Planificar mi tour",
      idioma_defecto: "es",
      idiomas_disponibles: ["es", "en", "fr", "ca"],
    },
    offers: [
      createOffer("tour-basic", "Tour básico", "Recorrido guiado de 2 horas por los puntos imprescindibles de la ciudad.", 32),
      createOffer("tour-premium", "Tour premium", "Ruta temática con acceso prioritario y grupo reducido.", 65),
      createOffer("tour-private", "Pack privado", "Itinerario personalizado con guía exclusivo y flexibilidad horaria.", 290),
    ],
  },
  ecommerce_retail: {
    account: {
      id: "sector-demo-ecommerce-retail",
      slug: "sector-demo-ecommerce-retail",
      nombre: "Nova Retail Lab (Demo)",
      activa: true,
      demo_publica: true,
      is_generic_sector_demo: true,
      sector: "ecommerce_retail",
      claim: "Acompaña al cliente en compra, soporte premium y postventa.",
      subtitulo: "Marca omnicanal con venta online y recogida en tienda.",
      descripcion_corta: "Ecommerce especializado en producto técnico con alto valor medio.",
      tono_marca: "claro, confiable y orientado a conversión",
      propuesta_valor: "Reduce abandono y mejora satisfacción con respuestas contextuales.",
      faqs_texto: ["¿Cuánto tarda el envío?", "¿Cómo gestiono una devolución?", "¿Tenéis soporte técnico?"],
      reglas_recomendacion: ["Si está comparando productos, ofrecer Asesoramiento de compra.", "Si compra producto complejo, recomendar Premium Support."],
      reglas_objeciones: ["Si duda por garantía, explicar cobertura y devolución.", "Si preocupa el envío, ofrecer opciones express y seguimiento."],
      prompts_sugeridos: ["Necesito ayuda para elegir producto", "¿Qué incluye premium support?", "¿Tenéis seguimiento postventa?"],
      cta: "Hablar con soporte comercial",
      idioma_defecto: "es",
      idiomas_disponibles: ["es", "en", "ca"],
    },
    offers: [
      createOffer("eco-advice", "Asesoramiento compra", "Sesión breve para recomendar el producto más adecuado por uso y presupuesto.", 0),
      createOffer("eco-premium", "Premium support", "Soporte prioritario por chat/email durante 30 días tras la compra.", 49),
      createOffer("eco-followup", "Seguimiento postventa", "Revisión de satisfacción y asistencia de configuración personalizada.", 29),
    ],
  },
  neutral: {
    account: {
      id: "sector-demo-neutral",
      slug: "sector-demo-neutral",
      nombre: "Demo Multisector (Genérica)",
      activa: true,
      demo_publica: true,
      is_generic_sector_demo: true,
      sector: "neutral",
      claim: "Assistència comercial adaptable a diferents sectors i fluxos de venda.",
      subtitulo: "Compte demostració neutral per validar experiència omnicanal.",
      descripcion_corta: "Context base per proves quan no hi ha sector específic seleccionat.",
      tono_marca: "professional, clar i amable",
      propuesta_valor: "Motor de conversa configurable per oferta, FAQs i regles sectorials.",
      faqs_texto: ["Com es configura el sector?", "Es poden usar comptes reals?", "Com es capturen leads?"],
      reglas_recomendacion: ["Primer pregunta objectiu i urgència del client.", "Després proposa l'oferta que millor encaixa."],
      reglas_objeciones: ["Si manca context, sol·licita 1-2 dades addicionals.", "Si hi ha dubtes de preu, aporta valor i següent pas."],
      prompts_sugeridos: ["Explica'm com funciona la demo", "Vull una recomanació inicial", "Ajuda'm a captar un lead"],
      cta: "Activar demo",
      idioma_defecto: "ca",
      idiomas_disponibles: ["ca", "es", "en"],
    },
    offers: [
      createOffer("neutral-basic", "Servei inicial", "Resposta i orientació comercial segons necessitat detectada.", 0),
      createOffer("neutral-pro", "Servei avançat", "Recomanació personalitzada amb proper pas i seguiment.", 90),
    ],
  },
};

export function getSectorDemoData(sector = "neutral") {
  const normalized = String(sector || "neutral").trim().toLowerCase();
  return demoSectorData[normalized] || demoSectorData.neutral;
}
