import { Briefcase, Building2, HeartPulse, House, ShoppingBag, Stethoscope, Utensils, Wine, Plane } from "lucide-react";

export const sectorPresets = {
  neutral: {
    id: "neutral",
    name: "General",
    claim: "Assistència intel·ligent per captació i seguiment comercial.",
    heroTitle: "Demo adaptable a múltiples sectors",
    heroSubtitle: "Configura missatges, casos d'ús i CTA sense reescriure el producte.",
    pains: ["Respostes lentes", "Leads sense context", "Seguiment irregular"],
    benefits: ["Respostes consistents", "Més conversió", "Traçabilitat clara"],
    prompts: ["Comenceu una conversa comercial", "Demana una proposta", "Explica disponibilitat"],
    cta: "Vull la meva demo sectorial",
    labels: { business: "Compte", services: "Solucions" },
    icon: Briefcase,
    prioritizedModules: ["overview", "activity", "next_steps"],
  },
  winery: {
    id: "winery",
    name: "Winery & enoturisme",
    claim: "Experiències i reserves assistides per IA.",
    heroTitle: "Transforma consultes en visites i reserves",
    heroSubtitle: "L'agent ajuda a recomanar experiències i a captar dades útils del visitant.",
    pains: ["Moltes preguntes repetitives", "Pèrdua de contactes", "Respostes fora d'horari"],
    benefits: ["Atenció 24/7", "Lead qualificat", "Millor experiència de marca"],
    prompts: ["Quina experiència recomanes per 4 persones?", "Teniu opcions premium?", "Puc reservar dissabte?"],
    cta: "Activar demo per enoturisme",
    labels: { business: "Celler", services: "Experiències" },
    icon: Wine,
    prioritizedModules: ["overview", "activity", "documents", "next_steps"],
  },
  clinic: {
    id: "clinic",
    name: "Clínica",
    claim: "Més eficiència en informació i prequalificació.",
    heroTitle: "Canalitza consultes de pacients amb claredat",
    heroSubtitle: "Un primer filtre útil abans de la gestió administrativa.",
    pains: ["Saturació de recepció", "Dubtes recurrents", "Baixa traçabilitat"],
    benefits: ["Derivació ordenada", "Temps alliberat", "Millor servei"],
    prompts: ["Com puc demanar primera visita?", "Quins serveis oferiu?", "Horaris disponibles"],
    cta: "Veure demo clínica",
    labels: { business: "Clínica", services: "Serveis" },
    icon: Stethoscope,
    prioritizedModules: ["overview", "timeline", "next_steps"],
  },
  realestate: { id: "realestate", name: "Immobiliari", claim: "Captació i qualificació de demanda.", heroTitle: "Respon millor i més ràpid", heroSubtitle: "Del primer contacte a la visita amb context centralitzat.", pains: ["Leads dispersos"], benefits: ["Qualificació inicial"], prompts: ["Busco pis de 3 habitacions"], cta: "Veure demo immobiliària", labels: { business: "Agència", services: "Actius" }, icon: House, prioritizedModules: ["overview", "activity"] },
  professional_services: { id: "professional_services", name: "Serveis professionals", claim: "Preventa estructurada.", heroTitle: "Converteix consultes en oportunitats", heroSubtitle: "Resposta guiada i seguiment senzill per al client.", pains: ["Briefings incomplets"], benefits: ["Més context des del primer dia"], prompts: ["Necessito assessorament"], cta: "Veure demo professional", labels: { business: "Firma", services: "Serveis" }, icon: Briefcase, prioritizedModules: ["overview", "documents", "next_steps"] },
  local_business: { id: "local_business", name: "Negoci local", claim: "Atenció comercial sempre disponible.", heroTitle: "No perdis cap oportunitat", heroSubtitle: "Respostes immediates amb to proper i coherent.", pains: ["Missatges no contestats"], benefits: ["Més confiança"], prompts: ["Teniu disponibilitat avui?"], cta: "Veure demo negoci local", labels: { business: "Negoci", services: "Servei" }, icon: Building2, prioritizedModules: ["overview", "activity"] },
  hospitality: { id: "hospitality", name: "Hospitality", claim: "Informació clara i upselling natural.", heroTitle: "Millora l'experiència del client", heroSubtitle: "Atenció àgil abans, durant i després de la reserva.", pains: ["Consultes repetitives"], benefits: ["Resposta instantània"], prompts: ["Teniu habitacions familiars?"], cta: "Veure demo hospitality", labels: { business: "Allotjament", services: "Paquets" }, icon: Utensils, prioritizedModules: ["overview", "activity", "timeline"] },
  tourism: { id: "tourism", name: "Turisme", claim: "Assistència de planificació i venda.", heroTitle: "Guia els viatgers des del primer clic", heroSubtitle: "Informació contextual i següents passos clars.", pains: ["Abandonament"], benefits: ["Més conversió"], prompts: ["Quines activitats recomaneu?"], cta: "Veure demo turisme", labels: { business: "Operador", services: "Experiències" }, icon: Plane, prioritizedModules: ["overview", "next_steps"] },
  health_wellness: { id: "health_wellness", name: "Salut i benestar", claim: "Atenció propera i informativa.", heroTitle: "Escala l'atenció amb sensibilitat", heroSubtitle: "Resol dubtes inicials i deriva amb criteri.", pains: ["Moltes consultes"], benefits: ["Més qualitat"], prompts: ["Quins tractaments oferiu?"], cta: "Veure demo salut", labels: { business: "Centre", services: "Programes" }, icon: HeartPulse, prioritizedModules: ["overview", "timeline"] },
  ecommerce_retail: { id: "ecommerce_retail", name: "Ecommerce & retail", claim: "Suport comercial i postvenda assistits.", heroTitle: "Més conversió, menys fricció", heroSubtitle: "Guia clients en compra, enviaments i incidències.", pains: ["Cistelles abandonades"], benefits: ["Resposta immediata"], prompts: ["Quan arriba la comanda?"], cta: "Veure demo ecommerce", labels: { business: "Marca", services: "Catàleg" }, icon: ShoppingBag, prioritizedModules: ["overview", "activity", "documents"] },
};

export const supportedSectors = Object.keys(sectorPresets);
